### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by minyatos** [sipeed/MaixPy-v1#260]
n-prefix riscv64-unknown-elf- config
-- SDK_PATH:/home/masteropencv/MaixPy
hello_world
Traceback (most recent call last):
  File "project.py", line 19, in <module>
    exec(f.read())
  File "<string>", line 37, in <module>
  File "/home/masteropencv/MaixPy/tools/flash/flash.py", line 12, in <module>
    import serial.tools.miniterm
ModuleNotFoundError: No module named 'serial'

**Comment by minyatos** [comment]
Python 3.6.10 :: Anaconda, Inc.
-- python command: python3, version: 
Traceback (most recent call last):
  File "/home/masteropencv/MaixPy/tools/kconfig/genconfig.py", line 12, in <module>
    import kconfiglib
ModuleNotFoundError: No module named 'kconfiglib'
CMake Error at /home/masteropencv/MaixPy/tools/cmake/compile.cmake:226 (message):
  Check Kconfig content
Call Stack (most recent call first):
  CMakeLists.txt:29 (project)
